### ISSUE TITLE
issues with native compliation when lib type is set to cdylib

### ISSUE THREAD

**Issue by hYdos** [stardust-enterprises/gradle-rust#11]
So i've been modifying the example to build win64, linux64, mac64, and macArm64 and for some reason cargo is trying to link with cc which I dont have installed on my machine. I've never had the issue with cargo and was wondering if there is anything i can do in my buildscript to fix it
![image](https://github.com/stardust-enterprises/gradle-rust/assets/25501603/f17a30d8-751d-4a04-a9ba-07932d7abc16)

My native subproject buildscript:
```KOTLIN
plugins {
    id("fr.stardustenterprises.rust.wrapper")
}

val nativeName = "test"

rust {
    release.set(true)
    command.set("cargo")
    cargoInstallTargets.set(true)

    targets {
        this += defaultTarget()

        create("linux64") {
            target = "x86_64-unknown-linux-gnu"
            outputName = "lib${nativeName}.so"
        }

        create("win64") {
            target = "x86_64-pc-windows-gnu"
            outputName = "${nativeName}.dll"
        }

        create("macOS-x86") {
            target = "x86_64-apple-darwin"
            outputName = "lib${nativeName}.dylib"

            command = "cargo"
            env += "CC" to "oa64-clang"
            env += "CXX" to "oa64-clang++"
        }

        create("macOS-aarch64") {
            target = "aarch64-apple-darwin"
            outputName = "lib${nativeName}.dylib"

            command = "cargo"
            env += "CC" to "oa64-clang"
            env += "CXX" to "oa64-clang++"
        }
    }
}
```

**Comment by qtdyn** [comment]
This might just be a cargo quirk, can't this be changed via the [.cargo/config.toml](https://github.com/stardust-enterprises/gradle-rust-example/blob/main/.cargo/config.toml) file? Does this happen without gradle-rust? I don't see any issue in your screenshot unfortunately.

**Comment by hYdos** [comment]
it doesnt happen without gradle-rust and i have the .cargo/config.toml

**Comment by qtdyn** [comment]
To be honest I don't really see what could've caused this, the plugin basically just [wraps the command execution](https://github.com/stardust-enterprises/gradle-rust/blob/trunk/src/main/kotlin/fr/stardustenterprises/gradle/rust/wrapper/task/BuildTask.kt#L145-L152) in a pretty bundle, so the only thing I could think off is you having different defaults that somehow aren't passed through? 

I haven't touched rustc in a hot minute, is there a way to debug log (both with and without gradle-rust) which linker (exact path) rustc is trying to use? (logs or screenshots at your convenience)

Also could you please show the error that you're getting when compiling with gradle-rust?

**Comment by qtdyn** [comment]
Hey :wave:, any update on this issue?

**Comment by hYdos** [comment]
give me 2 seconds to setup a project to test this again

**Comment by qtdyn** [comment]
Will reopen if updated :3
